export const Light = {
    primary:"white",
    secondary:"#FF4F28",
    width:{
        SideMenu:{
            open:'250px',
            close:"4rem",
        },
        BaseLayout:{
            open:"200px",
            close:"1rem"
        }
    },
    SideMenu:{
        Open:'200px',
        Close:"2rem",
        OpenActive:"#FF4F28",
        CloseActiveSec:"orange",
        CloseActive:"white"
    }
}